# Generated by Django 2.0.3 on 2018-03-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='contraseña',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
