# Generated by Django 2.0.2 on 2018-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Freno Y866', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='contrasena',
            field=models.CharField(default='123456', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
