# Generated by Django 2.0.2 on 2018-03-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0003_cliente_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineaventa',
            old_name='id_Venta',
            new_name='venta',
        ),
    ]
