# Generated by Django 2.0.2 on 2018-04-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0004_auto_20180323_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioA',
            new_name='precio1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioB',
            new_name='precio2',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioC',
            new_name='precio3',
        ),
    ]
