# Generated by Django 2.0.2 on 2018-04-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0005_auto_20180403_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_Proveedor',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='id_Vendedor',
            new_name='vendedor',
        ),
    ]
