# Generated by Django 2.0.2 on 2018-04-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0006_auto_20180403_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='id_Cliente',
            new_name='cliente',
        ),
    ]
