# Generated by Django 2.0.3 on 2018-04-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0006_auto_20180403_0545'),
        ('bdrepuestos', '0002_vendedor_contraseña'),
    ]

    operations = [
    ]
