# Generated by Django 2.0.2 on 2018-04-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0007_auto_20180405_0414'),
        ('bdrepuestos', '0007_merge_20180404_2308'),
    ]

    operations = [
    ]
