# Generated by Django 2.0.3 on 2018-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0007_merge_20180404_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='id_Cliente',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='contrasena',
        ),
    ]
