# Generated by Django 2.0.3 on 2018-04-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0008_auto_20180406_0044'),
        ('bdrepuestos', '0007_auto_20180405_0414'),
    ]

    operations = [
    ]
