# Generated by Django 2.0.2 on 2018-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0008_merge_20180406_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='contraseña',
            field=models.CharField(max_length=200),
        ),
    ]
