# Generated by Django 2.0.2 on 2018-04-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdrepuestos', '0011_auto_20180406_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='foraneo',
            new_name='cliente',
        ),
    ]
