# Generated by Django 2.0.3 on 2018-03-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('dpi', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(max_length=1)),
                ('direccion', models.TextField()),
                ('nit', models.CharField(max_length=20)),
                ('fecha_de_comienzo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField()),
                ('precioA', models.FloatField(default=0)),
                ('precioB', models.FloatField(default=0)),
                ('precioC', models.FloatField(default=0)),
                ('disponibilidad', models.IntegerField(default=0)),
                ('marca', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('total_ventas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_venta', models.DateField()),
                ('total', models.FloatField(default=0)),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdrepuestos.Cliente')),
                ('id_Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdrepuestos.Vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdrepuestos.Proveedor'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='id_Venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdrepuestos.Venta'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdrepuestos.Producto'),
        ),
    ]
